export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      rel="preload"
      href="/fonts/Gilroy-ExtraBold.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="gilroyExtraBoldWoff2Font"
    />,
    <link
      rel="preload"
      href="/fonts/Gilroy-ExtraBold.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
      key="gilroyExtraBoldWoffFont"
    />,
    <link
      rel="preload"
      href="/fonts/Gilroy-Light.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="gilroyLightWoff2Font"
    />,
    <link
      rel="preload"
      href="/fonts/Gilroy-Light.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
      key="gilroyLightWoffFont"
    />,
    <link
      rel="preload"
      href="/fonts/JetBrainsMono-Regular.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="jetbrainsMonoWoff2Font"
    />,
    <link
      rel="preload"
      href="/fonts/JetBrainsMono-Regular.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
      key="jetbrainsMonoWoffFont"
    />,
    <link
      rel="preload"
      href="/fonts/ClearSans-Light.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="clearSansLightWoff2Font"
    />,
    <link
      rel="preload"
      href="/fonts/ClearSans-Light.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
      key="clearSansLightWoffFont"
    />,
    <link
      rel="preload"
      href="/fonts/ClearSans-Thin.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="clearSansThinWoff2Font"
    />,
    <link
      rel="preload"
      href="/fonts/ClearSans-Thin.woff"
      as="font"
      type="font/woff"
      crossOrigin="anonymous"
      key="clearSansThinWoffFont"
    />,
  ])
}
