version: 2

workflows:
  version: 2
  build:
    jobs:
      - prep-deps

jobs:
  prep-deps:
    docker:
      - image: circleci/node:12.9.0
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Prepare npm dependencies
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules