version: 2

workflows:
  version: 2
  build:
    jobs:
      - prep-deps
      - build-site:
          requires:
            - prep-deps

defaults: &defaults
  docker:
    - image: circleci/node:12.9.0

jobs:
  prep-deps:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: Prepare npm dependencies
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  build-site:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Gatsby site
          command: npm run build