indexConfig:
  greeting: Hi, I am
  name: Gali Armero
  tagline: I build things that simplify.
  aboutIntro: >-
    Hello! My name is Gali -- short for Galileo.
    I'm a full stack software engineer from the Philippines.
    I find joy in creating applications that make people's lives easier.
    I specialize in building performant backends and hiding complexity
    with clean, intuitive user interfaces.
    Here are some of the technologies I work with:
  techSkills:
    - JavaScript
    - Node.js
    - Express
    - GraphQL
    - React
    - Gatsby
    - Docker
    - HTML & CSS
    - Java & Spring
    - Python
  aboutPersonal: >-
    I grew up in the small town of <a href="https://en.wikipedia.org/wiki/Canaman,_Camarines_Sur">Canaman</a>
    in Camarines Sur province. Soon after graduating at the <a href="https://www.adnu.edu.ph/">Ateneo de Naga University</a>
    in 2014, I took my printed maps and talents to Manila and joined <a href="https://www.nokia.com/networks/">Nokia</a>
    where I am currently working on a suite of troubleshooting and analytics tools for telecom service providers worldwide.


    When not coding, I enjoy eating, exploring new places, listening to podcasts,
    playing basketball, and following my Lakers.


    I also write about my learnings, insights and experiences in my <a href="./blog">blog</a>.
  copyrightYear: 2020
