profile:
  greeting: Hi, I am
  name: Gali Armero
  tagline: I love building things that simplify.
  briefBio: >-
    Gali Armero is a software engineer.
    He enjoys building performant distributed systems and
    hiding complexity with clean, intuitive user interfaces.
  blogBioAfterName: >-
    is a software engineer from the Philippines. He is amused
    by elegant software solutions, new places, ugly delicious food,
    and the sound of a basketball swishing through the hoop.
  blogDescription: Insights of a tech guy in perpetual search for answers.
  aboutIntro: >-
    Hello! My name is Gali -- short for Galileo.
    I'm a software engineer from the Philippines.
    I find joy in creating applications that make people's lives easier.
    Building high-load distributed systems piques my interest. I also relish
    the art of hiding complexity with clean, intuititve user interfaces.
    Here are some of the tech I've worked on:
  techSkills:
    - Java
    - Spring Boot
    - JavaScript
    - Node.js
    - Express
    - Python
    - React
    - Gatsby
    - HTML & CSS
    - MongoDB
    - MySQL
    - GraphQL
    - Docker
    - Humio
    - Grafana
    - Jaeger
  aboutPersonal: >-
    I grew up in the small town of <a href="https://en.wikipedia.org/wiki/Canaman,_Camarines_Sur">Canaman</a>
    in Camarines Sur province. Soon after graduating at the <a href="https://www.adnu.edu.ph/">Ateneo de Naga University</a>
    in 2014, I took my printed maps and talents to Manila and joined <a href="https://www.nokia.com/networks/">Nokia</a>
    where I worked on a suite of troubleshooting and analytics tools for telecom service providers worldwide.

    Most recently, I worked as a Software Development Engineer at Remitly, a digital payments company offering
    international money transfers to over 135 countries (<a href="https://www.google.com/finance/quote/RELY:NASDAQ">RELY:NASDAQ</a>,
    since Sep 2021). I was part of the Destination Experience team that expands the global disbursement network
    to give customers a diverse set of receiving-end options while ensuring that the system that moves billions
    of dollars a year is fast, reliable, and scalable.

    When not coding, I enjoy eating, exploring new places, biking, listening to podcasts,
    playing basketball, and following my Lakers.

    I also write about my learnings, insights and experiences in my <a href="#latestBlogPosts">blog</a>.
menuOptions:
  - title: About
    link: '#about'
  - title: Blog
    link: '/blog'
    isInternal: true
  - title: Contact
    link: '#contact'
socialMediaLinks:
  - id: github
    link: https://github.com/galiarmero
  - id: linkedin
    link: https://www.linkedin.com/in/galileoarmero
  - id: stackoverflow
    link: https://stackoverflow.com/users/8712967/galiarmero
  - id: twitter
    link: https://twitter.com/galiarmero
    username: galiarmero
    isHidden: true
  - id: instagram
    link: https://www.instagram.com/galiarmero/
    isHidden: true
siteBaseUrl: https://galiarmero.dev
nakedDomain: galiarmero.dev
projectSourceUrl: https://github.com/galiarmero/galiarmero.dev
copyrightYear: 2022