socialMediaConfig:
  - id: github
    link: https://github.com/galiarmero
  - id: linkedin
    link: https://www.linkedin.com/in/galileoarmero
  - id: twitter
    link: https://twitter.com/galiarmero
  - id: instagram
    link: https://www.instagram.com/galiarmero/
